---
- name: install-nfs-server
  yum:
    name: nfs-utils
    state: latest
- name: copy/etc/export
  template:
    src=exports.j2
    dest=/etc/exports
    owner=root
    group=root
    mode=755
- name: restart-nfs-server
  service: "name=nfs-server.service state=restarted enabled=yes"
